version: '3.6'
services:
  react:
    container_name: node
    image: 'node:latest'
    working_dir: /home/node/app
    command:
      - /bin/sh
      - '-c'
      - 'npm install && npm build'
    ports:
      - '3000:3000'
    volumes:
      - '.:/home/node/app'
      - '/home/node/app/node_modules'